// <auto-generated />
using System;
using HealthPairDataAccess.DataModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace HealthPairDataAccess.Migrations
{
    [DbContext(typeof(HealthPairContext))]
    [Migration("20200512180753_migrationname")]
    partial class migrationname
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("HealthPairDataAccess.DataModels.Data_Appointment", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer");

                    b.Property<int>("ProviderId")
                        .HasColumnType("integer");

                    b.HasKey("AppointmentId");

                    b.HasIndex("PatientId");

                    b.HasIndex("ProviderId");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            AppointmentId = 1,
                            AppointmentDate = new DateTime(2020, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 3,
                            ProviderId = 1
                        },
                        new
                        {
                            AppointmentId = 2,
                            AppointmentDate = new DateTime(2020, 6, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 2,
                            ProviderId = 3
                        },
                        new
                        {
                            AppointmentId = 3,
                            AppointmentDate = new DateTime(2020, 5, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 1,
                            ProviderId = 2
                        });
                });

            modelBuilder.Entity("HealthPairDataAccess.DataModels.Data_Facility", b =>
                {
                    b.Property<int>("FacilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("FacilityAddress1")
                        .IsRequired()
                        .HasColumnType("character varying(120)")
                        .HasMaxLength(120);

                    b.Property<string>("FacilityCity")
                        .IsRequired()
                        .HasColumnType("character varying(40)")
                        .HasMaxLength(40);

                    b.Property<string>("FacilityName")
                        .IsRequired()
                        .HasColumnType("character varying(80)")
                        .HasMaxLength(80);

                    b.Property<long>("FacilityPhoneNumber")
                        .HasColumnType("bigint");

                    b.Property<string>("FacilityState")
                        .IsRequired()
                        .HasColumnType("character varying(40)")
                        .HasMaxLength(40);

                    b.Property<int>("FacilityZipcode")
                        .HasColumnType("integer");

                    b.HasKey("FacilityId");

                    b.ToTable("Facilities");

                    b.HasData(
                        new
                        {
                            FacilityId = 1,
                            FacilityAddress1 = "1700 James Bowie Drive",
                            FacilityCity = "Baytown",
                            FacilityName = "Houston Methodist San Jacinto Hospital Alexander Campus",
                            FacilityPhoneNumber = 2814208765L,
                            FacilityState = "TX",
                            FacilityZipcode = 77520
                        },
                        new
                        {
                            FacilityId = 2,
                            FacilityAddress1 = "16750 Red Oak Drive",
                            FacilityCity = "Houston",
                            FacilityName = "Providence Hospital of North Houston LLC",
                            FacilityPhoneNumber = 2814537110L,
                            FacilityState = "TX",
                            FacilityZipcode = 77090
                        },
                        new
                        {
                            FacilityId = 3,
                            FacilityAddress1 = "301 West Expressway 83",
                            FacilityCity = "McAllen",
                            FacilityName = "McCallen Medical Center",
                            FacilityPhoneNumber = 9566324000L,
                            FacilityState = "TX",
                            FacilityZipcode = 78590
                        },
                        new
                        {
                            FacilityId = 4,
                            FacilityAddress1 = "215 Chisholm Trail",
                            FacilityCity = "Jacksboro",
                            FacilityName = "Faith Community Hospital",
                            FacilityPhoneNumber = 9405676633L,
                            FacilityState = "TX",
                            FacilityZipcode = 76458
                        },
                        new
                        {
                            FacilityId = 5,
                            FacilityAddress1 = "4000 24th Street",
                            FacilityCity = "Lubbock",
                            FacilityName = "Covenant Medical Center – Lakeside",
                            FacilityPhoneNumber = 8067250536L,
                            FacilityState = "TX",
                            FacilityZipcode = 79410
                        },
                        new
                        {
                            FacilityId = 6,
                            FacilityAddress1 = "25440 I 45 North",
                            FacilityCity = "The Woodlands",
                            FacilityName = "Woodlands Specialty Hospita",
                            FacilityPhoneNumber = 2816028160L,
                            FacilityState = "TX",
                            FacilityZipcode = 77386
                        },
                        new
                        {
                            FacilityId = 7,
                            FacilityAddress1 = "600 Elizabeth Street",
                            FacilityCity = "Corpus Christi",
                            FacilityName = "Christus Spohn Hospital Corpus Christi Shoreline",
                            FacilityPhoneNumber = 3619024690L,
                            FacilityState = "TX",
                            FacilityZipcode = 78404
                        },
                        new
                        {
                            FacilityId = 8,
                            FacilityAddress1 = "13725 Northwest Blvd",
                            FacilityCity = "Corpus Christi",
                            FacilityName = "The Corpus Christi Medical Center – Northwest",
                            FacilityPhoneNumber = 3617674300L,
                            FacilityState = "TX",
                            FacilityZipcode = 78410
                        },
                        new
                        {
                            FacilityId = 9,
                            FacilityAddress1 = "1300 N Main Ave",
                            FacilityCity = "Big Lake",
                            FacilityName = "Reagan Memorial Hospital",
                            FacilityPhoneNumber = 3258842561L,
                            FacilityState = "TX",
                            FacilityZipcode = 76932
                        },
                        new
                        {
                            FacilityId = 10,
                            FacilityAddress1 = "1975 Alpha, Suite 100",
                            FacilityCity = "Rockwall",
                            FacilityName = "Baylor Emergency Medical Center",
                            FacilityPhoneNumber = 2142946200L,
                            FacilityState = "TX",
                            FacilityZipcode = 75087
                        },
                        new
                        {
                            FacilityId = 11,
                            FacilityAddress1 = "620 South Main, Suite 100",
                            FacilityCity = "Keller",
                            FacilityName = "Baylor Emergency Medical Center",
                            FacilityPhoneNumber = 2142946100L,
                            FacilityState = "TX",
                            FacilityZipcode = 76248
                        },
                        new
                        {
                            FacilityId = 12,
                            FacilityAddress1 = "12500 South Freeway, Suite 100",
                            FacilityCity = "Burleson",
                            FacilityName = "Baylor Emergency Medical Center",
                            FacilityPhoneNumber = 2142946250L,
                            FacilityState = "TX",
                            FacilityZipcode = 76028
                        },
                        new
                        {
                            FacilityId = 13,
                            FacilityAddress1 = "1776 North Us 287, Suite 100",
                            FacilityCity = "Mansfield",
                            FacilityName = "Baylor Emergency Medical Center",
                            FacilityPhoneNumber = 2142946300L,
                            FacilityState = "TX",
                            FacilityZipcode = 76063
                        },
                        new
                        {
                            FacilityId = 14,
                            FacilityAddress1 = "5500 Colleyville Boulevard",
                            FacilityCity = "Colleyville",
                            FacilityName = "Baylor Emergency Medical Center",
                            FacilityPhoneNumber = 2142946350L,
                            FacilityState = "TX",
                            FacilityZipcode = 76034
                        },
                        new
                        {
                            FacilityId = 15,
                            FacilityAddress1 = "3101 North Tarrant Parkway",
                            FacilityCity = "Fort Worth",
                            FacilityName = "Medical Center of Alliance",
                            FacilityPhoneNumber = 8176391100L,
                            FacilityState = "TX",
                            FacilityZipcode = 76177
                        });
                });

            modelBuilder.Entity("HealthPairDataAccess.DataModels.Data_Insurance", b =>
                {
                    b.Property<int>("InsuranceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("InsuranceName")
                        .IsRequired()
                        .HasColumnType("character varying(80)")
                        .HasMaxLength(80);

                    b.HasKey("InsuranceId");

                    b.ToTable("Insurances");

                    b.HasData(
                        new
                        {
                            InsuranceId = 1,
                            InsuranceName = "Cigna"
                        },
                        new
                        {
                            InsuranceId = 2,
                            InsuranceName = "Humana"
                        },
                        new
                        {
                            InsuranceId = 3,
                            InsuranceName = "Community"
                        },
                        new
                        {
                            InsuranceId = 4,
                            InsuranceName = "Molina"
                        },
                        new
                        {
                            InsuranceId = 5,
                            InsuranceName = "FirstCare"
                        },
                        new
                        {
                            InsuranceId = 6,
                            InsuranceName = "Superior"
                        },
                        new
                        {
                            InsuranceId = 7,
                            InsuranceName = "Christus"
                        },
                        new
                        {
                            InsuranceId = 8,
                            InsuranceName = "Celtic"
                        },
                        new
                        {
                            InsuranceId = 9,
                            InsuranceName = "Sendero"
                        },
                        new
                        {
                            InsuranceId = 10,
                            InsuranceName = "EmblemHealth"
                        },
                        new
                        {
                            InsuranceId = 11,
                            InsuranceName = "Wellcare"
                        },
                        new
                        {
                            InsuranceId = 12,
                            InsuranceName = "CVS"
                        },
                        new
                        {
                            InsuranceId = 13,
                            InsuranceName = "Independence Health Group Inc."
                        },
                        new
                        {
                            InsuranceId = 14,
                            InsuranceName = "Highmark Group"
                        },
                        new
                        {
                            InsuranceId = 15,
                            InsuranceName = "None (Cash)"
                        });
                });

            modelBuilder.Entity("HealthPairDataAccess.DataModels.Data_InsuranceProvider", b =>
                {
                    b.Property<int>("IPId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("InsuranceId")
                        .HasColumnType("integer");

                    b.Property<int>("ProviderId")
                        .HasColumnType("integer");

                    b.HasKey("IPId");

                    b.HasIndex("InsuranceId");

                    b.HasIndex("ProviderId");

                    b.ToTable("InsuranceProviders");

                    b.HasData(
                        new
                        {
                            IPId = 2,
                            InsuranceId = 1,
                            ProviderId = 2
                        },
                        new
                        {
                            IPId = 46,
                            InsuranceId = 1,
                            ProviderId = 4
                        },
                        new
                        {
                            IPId = 47,
                            InsuranceId = 1,
                            ProviderId = 5
                        },
                        new
                        {
                            IPId = 49,
                            InsuranceId = 1,
                            ProviderId = 7
                        },
                        new
                        {
                            IPId = 52,
                            InsuranceId = 1,
                            ProviderId = 10
                        },
                        new
                        {
                            IPId = 53,
                            InsuranceId = 1,
                            ProviderId = 11
                        },
                        new
                        {
                            IPId = 55,
                            InsuranceId = 1,
                            ProviderId = 13
                        },
                        new
                        {
                            IPId = 56,
                            InsuranceId = 1,
                            ProviderId = 14
                        },
                        new
                        {
                            IPId = 57,
                            InsuranceId = 1,
                            ProviderId = 15
                        },
                        new
                        {
                            IPId = 59,
                            InsuranceId = 1,
                            ProviderId = 17
                        },
                        new
                        {
                            IPId = 62,
                            InsuranceId = 1,
                            ProviderId = 20
                        },
                        new
                        {
                            IPId = 66,
                            InsuranceId = 1,
                            ProviderId = 24
                        },
                        new
                        {
                            IPId = 69,
                            InsuranceId = 1,
                            ProviderId = 27
                        },
                        new
                        {
                            IPId = 70,
                            InsuranceId = 1,
                            ProviderId = 28
                        },
                        new
                        {
                            IPId = 73,
                            InsuranceId = 1,
                            ProviderId = 31
                        },
                        new
                        {
                            IPId = 74,
                            InsuranceId = 1,
                            ProviderId = 32
                        },
                        new
                        {
                            IPId = 76,
                            InsuranceId = 1,
                            ProviderId = 34
                        },
                        new
                        {
                            IPId = 77,
                            InsuranceId = 1,
                            ProviderId = 35
                        },
                        new
                        {
                            IPId = 78,
                            InsuranceId = 1,
                            ProviderId = 36
                        },
                        new
                        {
                            IPId = 82,
                            InsuranceId = 1,
                            ProviderId = 40
                        },
                        new
                        {
                            IPId = 4,
                            InsuranceId = 2,
                            ProviderId = 1
                        },
                        new
                        {
                            IPId = 5,
                            InsuranceId = 2,
                            ProviderId = 2
                        },
                        new
                        {
                            IPId = 6,
                            InsuranceId = 2,
                            ProviderId = 3
                        },
                        new
                        {
                            IPId = 90,
                            InsuranceId = 2,
                            ProviderId = 8
                        },
                        new
                        {
                            IPId = 91,
                            InsuranceId = 2,
                            ProviderId = 9
                        },
                        new
                        {
                            IPId = 92,
                            InsuranceId = 2,
                            ProviderId = 10
                        },
                        new
                        {
                            IPId = 93,
                            InsuranceId = 2,
                            ProviderId = 11
                        },
                        new
                        {
                            IPId = 94,
                            InsuranceId = 2,
                            ProviderId = 12
                        },
                        new
                        {
                            IPId = 95,
                            InsuranceId = 2,
                            ProviderId = 13
                        },
                        new
                        {
                            IPId = 96,
                            InsuranceId = 2,
                            ProviderId = 14
                        },
                        new
                        {
                            IPId = 97,
                            InsuranceId = 2,
                            ProviderId = 15
                        },
                        new
                        {
                            IPId = 100,
                            InsuranceId = 2,
                            ProviderId = 18
                        },
                        new
                        {
                            IPId = 101,
                            InsuranceId = 2,
                            ProviderId = 19
                        },
                        new
                        {
                            IPId = 107,
                            InsuranceId = 2,
                            ProviderId = 25
                        },
                        new
                        {
                            IPId = 108,
                            InsuranceId = 2,
                            ProviderId = 26
                        },
                        new
                        {
                            IPId = 109,
                            InsuranceId = 2,
                            ProviderId = 27
                        },
                        new
                        {
                            IPId = 117,
                            InsuranceId = 2,
                            ProviderId = 35
                        },
                        new
                        {
                            IPId = 118,
                            InsuranceId = 2,
                            ProviderId = 36
                        },
                        new
                        {
                            IPId = 119,
                            InsuranceId = 2,
                            ProviderId = 37
                        },
                        new
                        {
                            IPId = 120,
                            InsuranceId = 2,
                            ProviderId = 38
                        },
                        new
                        {
                            IPId = 7,
                            InsuranceId = 3,
                            ProviderId = 1
                        },
                        new
                        {
                            IPId = 9,
                            InsuranceId = 3,
                            ProviderId = 3
                        },
                        new
                        {
                            IPId = 10,
                            InsuranceId = 4,
                            ProviderId = 1
                        },
                        new
                        {
                            IPId = 12,
                            InsuranceId = 4,
                            ProviderId = 3
                        },
                        new
                        {
                            IPId = 13,
                            InsuranceId = 5,
                            ProviderId = 1
                        },
                        new
                        {
                            IPId = 16,
                            InsuranceId = 6,
                            ProviderId = 1
                        },
                        new
                        {
                            IPId = 18,
                            InsuranceId = 6,
                            ProviderId = 3
                        },
                        new
                        {
                            IPId = 19,
                            InsuranceId = 7,
                            ProviderId = 1
                        },
                        new
                        {
                            IPId = 21,
                            InsuranceId = 7,
                            ProviderId = 3
                        },
                        new
                        {
                            IPId = 22,
                            InsuranceId = 8,
                            ProviderId = 1
                        },
                        new
                        {
                            IPId = 24,
                            InsuranceId = 8,
                            ProviderId = 3
                        },
                        new
                        {
                            IPId = 26,
                            InsuranceId = 9,
                            ProviderId = 2
                        },
                        new
                        {
                            IPId = 27,
                            InsuranceId = 9,
                            ProviderId = 3
                        },
                        new
                        {
                            IPId = 28,
                            InsuranceId = 10,
                            ProviderId = 1
                        },
                        new
                        {
                            IPId = 31,
                            InsuranceId = 11,
                            ProviderId = 1
                        },
                        new
                        {
                            IPId = 32,
                            InsuranceId = 11,
                            ProviderId = 2
                        },
                        new
                        {
                            IPId = 33,
                            InsuranceId = 11,
                            ProviderId = 3
                        },
                        new
                        {
                            IPId = 34,
                            InsuranceId = 12,
                            ProviderId = 1
                        },
                        new
                        {
                            IPId = 35,
                            InsuranceId = 12,
                            ProviderId = 2
                        },
                        new
                        {
                            IPId = 38,
                            InsuranceId = 13,
                            ProviderId = 2
                        },
                        new
                        {
                            IPId = 41,
                            InsuranceId = 14,
                            ProviderId = 2
                        },
                        new
                        {
                            IPId = 42,
                            InsuranceId = 14,
                            ProviderId = 3
                        },
                        new
                        {
                            IPId = 43,
                            InsuranceId = 15,
                            ProviderId = 1
                        },
                        new
                        {
                            IPId = 45,
                            InsuranceId = 15,
                            ProviderId = 3
                        },
                        new
                        {
                            IPId = 83,
                            InsuranceId = 1,
                            ProviderId = 41
                        },
                        new
                        {
                            IPId = 84,
                            InsuranceId = 1,
                            ProviderId = 42
                        },
                        new
                        {
                            IPId = 85,
                            InsuranceId = 1,
                            ProviderId = 43
                        });
                });

            modelBuilder.Entity("HealthPairDataAccess.DataModels.Data_Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("InsuranceId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("PatientAddress1")
                        .IsRequired()
                        .HasColumnType("character varying(120)")
                        .HasMaxLength(120);

                    b.Property<DateTime>("PatientBirthDay")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("PatientCity")
                        .IsRequired()
                        .HasColumnType("character varying(40)")
                        .HasMaxLength(40);

                    b.Property<string>("PatientEmail")
                        .IsRequired()
                        .HasColumnType("character varying(120)")
                        .HasMaxLength(120);

                    b.Property<string>("PatientFirstName")
                        .IsRequired()
                        .HasColumnType("character varying(80)")
                        .HasMaxLength(80);

                    b.Property<string>("PatientLastName")
                        .IsRequired()
                        .HasColumnType("character varying(80)")
                        .HasMaxLength(80);

                    b.Property<string>("PatientPassword")
                        .IsRequired()
                        .HasColumnType("character varying(80)")
                        .HasMaxLength(80);

                    b.Property<long>("PatientPhoneNumber")
                        .HasColumnType("bigint");

                    b.Property<string>("PatientState")
                        .IsRequired()
                        .HasColumnType("character varying(40)")
                        .HasMaxLength(40);

                    b.Property<int>("PatientZipcode")
                        .HasColumnType("integer");

                    b.HasKey("PatientId");

                    b.HasIndex("InsuranceId");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            PatientId = 1,
                            InsuranceId = 1,
                            IsAdmin = true,
                            PatientAddress1 = "8401 Ronnie St",
                            PatientBirthDay = new DateTime(2000, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientCity = "Fort Worth",
                            PatientEmail = "x21ssy0@si.edu",
                            PatientFirstName = "James",
                            PatientLastName = "Matthews",
                            PatientPassword = "Password1",
                            PatientPhoneNumber = 7167787419L,
                            PatientState = "TX",
                            PatientZipcode = 76108
                        },
                        new
                        {
                            PatientId = 2,
                            InsuranceId = 3,
                            IsAdmin = true,
                            PatientAddress1 = "2500 Victory Ave",
                            PatientBirthDay = new DateTime(1988, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientCity = "Dallas",
                            PatientEmail = "woxmony1@shop-pro.jp",
                            PatientFirstName = "Jeff",
                            PatientLastName = "Harbor",
                            PatientPassword = "Password2",
                            PatientPhoneNumber = 3619033062L,
                            PatientState = "TX",
                            PatientZipcode = 75201
                        },
                        new
                        {
                            PatientId = 3,
                            InsuranceId = 5,
                            IsAdmin = false,
                            PatientAddress1 = "5919 Peg Street",
                            PatientBirthDay = new DateTime(2002, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientCity = "Houston",
                            PatientEmail = "lsiward2@cnbc.com",
                            PatientFirstName = "Zack",
                            PatientLastName = "Lomar",
                            PatientPassword = "Password3",
                            PatientPhoneNumber = 2452488647L,
                            PatientState = "TX",
                            PatientZipcode = 77092
                        },
                        new
                        {
                            PatientId = 4,
                            InsuranceId = 7,
                            IsAdmin = false,
                            PatientAddress1 = "10810 Spring Cypress Rd.",
                            PatientBirthDay = new DateTime(1999, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientCity = "Tomball",
                            PatientEmail = "mizzs3@microsoft.com",
                            PatientFirstName = "Robert",
                            PatientLastName = "Blevins",
                            PatientPassword = "Password4",
                            PatientPhoneNumber = 8823701130L,
                            PatientState = "TX",
                            PatientZipcode = 77375
                        },
                        new
                        {
                            PatientId = 5,
                            InsuranceId = 7,
                            IsAdmin = false,
                            PatientAddress1 = "10810 Spring Cypress Rd.",
                            PatientBirthDay = new DateTime(1999, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientCity = "Tomball",
                            PatientEmail = "xabc23@microsoft.com",
                            PatientFirstName = "Don",
                            PatientLastName = "Jarrell",
                            PatientPassword = "Password4",
                            PatientPhoneNumber = 8823701130L,
                            PatientState = "TX",
                            PatientZipcode = 77375
                        },
                        new
                        {
                            PatientId = 6,
                            InsuranceId = 1,
                            IsAdmin = true,
                            PatientAddress1 = "123 Test Street",
                            PatientBirthDay = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientCity = "Test City",
                            PatientEmail = "TestEmail@test.com",
                            PatientFirstName = "TestPatientFirstName",
                            PatientLastName = "TestPatientLastName",
                            PatientPassword = "TestPassword",
                            PatientPhoneNumber = 1234567890L,
                            PatientState = "Test State",
                            PatientZipcode = 12345
                        });
                });

            modelBuilder.Entity("HealthPairDataAccess.DataModels.Data_Provider", b =>
                {
                    b.Property<int>("ProviderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("FacilityId")
                        .HasColumnType("integer");

                    b.Property<string>("ProviderFirstName")
                        .IsRequired()
                        .HasColumnType("character varying(80)")
                        .HasMaxLength(80);

                    b.Property<string>("ProviderLastName")
                        .IsRequired()
                        .HasColumnType("character varying(80)")
                        .HasMaxLength(80);

                    b.Property<long>("ProviderPhoneNumber")
                        .HasColumnType("bigint");

                    b.Property<int>("SpecialtyId")
                        .HasColumnType("integer");

                    b.HasKey("ProviderId");

                    b.HasIndex("FacilityId");

                    b.HasIndex("SpecialtyId");

                    b.ToTable("Providers");

                    b.HasData(
                        new
                        {
                            ProviderId = 1,
                            FacilityId = 1,
                            ProviderFirstName = "Josh",
                            ProviderLastName = "Krutz",
                            ProviderPhoneNumber = 7167787419L,
                            SpecialtyId = 6
                        },
                        new
                        {
                            ProviderId = 2,
                            FacilityId = 2,
                            ProviderFirstName = "Zack",
                            ProviderLastName = "Shorrell",
                            ProviderPhoneNumber = 3619033062L,
                            SpecialtyId = 13
                        },
                        new
                        {
                            ProviderId = 3,
                            FacilityId = 3,
                            ProviderFirstName = "Jack",
                            ProviderLastName = "Jefferies",
                            ProviderPhoneNumber = 2452488647L,
                            SpecialtyId = 5
                        },
                        new
                        {
                            ProviderId = 4,
                            FacilityId = 4,
                            ProviderFirstName = "John",
                            ProviderLastName = "Rushe",
                            ProviderPhoneNumber = 8823701130L,
                            SpecialtyId = 8
                        },
                        new
                        {
                            ProviderId = 5,
                            FacilityId = 5,
                            ProviderFirstName = "Jeremiah",
                            ProviderLastName = "Brolin",
                            ProviderPhoneNumber = 9016226625L,
                            SpecialtyId = 11
                        },
                        new
                        {
                            ProviderId = 6,
                            FacilityId = 6,
                            ProviderFirstName = "Maury",
                            ProviderLastName = "Chitter",
                            ProviderPhoneNumber = 2577977019L,
                            SpecialtyId = 4
                        },
                        new
                        {
                            ProviderId = 7,
                            FacilityId = 7,
                            ProviderFirstName = "Philomena",
                            ProviderLastName = "Capon",
                            ProviderPhoneNumber = 2834986226L,
                            SpecialtyId = 8
                        },
                        new
                        {
                            ProviderId = 8,
                            FacilityId = 8,
                            ProviderFirstName = "Michail",
                            ProviderLastName = "Minkin",
                            ProviderPhoneNumber = 4487593448L,
                            SpecialtyId = 4
                        },
                        new
                        {
                            ProviderId = 9,
                            FacilityId = 9,
                            ProviderFirstName = "Boothe",
                            ProviderLastName = "Gurrado",
                            ProviderPhoneNumber = 9373233203L,
                            SpecialtyId = 2
                        },
                        new
                        {
                            ProviderId = 10,
                            FacilityId = 10,
                            ProviderFirstName = "Kendall",
                            ProviderLastName = "Mulqueen",
                            ProviderPhoneNumber = 9033544326L,
                            SpecialtyId = 1
                        },
                        new
                        {
                            ProviderId = 11,
                            FacilityId = 11,
                            ProviderFirstName = "Onfre",
                            ProviderLastName = "Grazier",
                            ProviderPhoneNumber = 8503233858L,
                            SpecialtyId = 14
                        },
                        new
                        {
                            ProviderId = 12,
                            FacilityId = 12,
                            ProviderFirstName = "Mauricio",
                            ProviderLastName = "Rowes",
                            ProviderPhoneNumber = 3259067361L,
                            SpecialtyId = 8
                        },
                        new
                        {
                            ProviderId = 13,
                            FacilityId = 13,
                            ProviderFirstName = "Elana",
                            ProviderLastName = "Dollman",
                            ProviderPhoneNumber = 8696441600L,
                            SpecialtyId = 6
                        },
                        new
                        {
                            ProviderId = 14,
                            FacilityId = 14,
                            ProviderFirstName = "Georg",
                            ProviderLastName = "Yakunchikov",
                            ProviderPhoneNumber = 3464020514L,
                            SpecialtyId = 10
                        },
                        new
                        {
                            ProviderId = 15,
                            FacilityId = 15,
                            ProviderFirstName = "Nanny",
                            ProviderLastName = "Stead",
                            ProviderPhoneNumber = 7705745366L,
                            SpecialtyId = 3
                        },
                        new
                        {
                            ProviderId = 16,
                            FacilityId = 1,
                            ProviderFirstName = "Jorie",
                            ProviderLastName = "Atwool",
                            ProviderPhoneNumber = 9363687510L,
                            SpecialtyId = 8
                        },
                        new
                        {
                            ProviderId = 17,
                            FacilityId = 2,
                            ProviderFirstName = "Alfons",
                            ProviderLastName = "Shee",
                            ProviderPhoneNumber = 6445427083L,
                            SpecialtyId = 11
                        },
                        new
                        {
                            ProviderId = 18,
                            FacilityId = 3,
                            ProviderFirstName = "Netta",
                            ProviderLastName = "Fincken",
                            ProviderPhoneNumber = 5252048919L,
                            SpecialtyId = 7
                        },
                        new
                        {
                            ProviderId = 19,
                            FacilityId = 4,
                            ProviderFirstName = "Melli",
                            ProviderLastName = "Hansford",
                            ProviderPhoneNumber = 5024459183L,
                            SpecialtyId = 14
                        },
                        new
                        {
                            ProviderId = 20,
                            FacilityId = 5,
                            ProviderFirstName = "Kathryne",
                            ProviderLastName = "Pawlaczyk",
                            ProviderPhoneNumber = 6981610466L,
                            SpecialtyId = 14
                        },
                        new
                        {
                            ProviderId = 21,
                            FacilityId = 6,
                            ProviderFirstName = "Dex",
                            ProviderLastName = "Rawstron",
                            ProviderPhoneNumber = 5243227555L,
                            SpecialtyId = 13
                        },
                        new
                        {
                            ProviderId = 22,
                            FacilityId = 7,
                            ProviderFirstName = "Dorie",
                            ProviderLastName = "O'Dreain",
                            ProviderPhoneNumber = 5123716488L,
                            SpecialtyId = 4
                        },
                        new
                        {
                            ProviderId = 23,
                            FacilityId = 8,
                            ProviderFirstName = "Leonora",
                            ProviderLastName = "Pitford",
                            ProviderPhoneNumber = 2138363970L,
                            SpecialtyId = 10
                        },
                        new
                        {
                            ProviderId = 24,
                            FacilityId = 9,
                            ProviderFirstName = "Whitney",
                            ProviderLastName = "Sevior",
                            ProviderPhoneNumber = 6174183997L,
                            SpecialtyId = 1
                        },
                        new
                        {
                            ProviderId = 25,
                            FacilityId = 10,
                            ProviderFirstName = "Zora",
                            ProviderLastName = "Paolucci",
                            ProviderPhoneNumber = 1909364291L,
                            SpecialtyId = 8
                        },
                        new
                        {
                            ProviderId = 26,
                            FacilityId = 11,
                            ProviderFirstName = "Jayson",
                            ProviderLastName = "Wookey",
                            ProviderPhoneNumber = 8982665744L,
                            SpecialtyId = 10
                        },
                        new
                        {
                            ProviderId = 27,
                            FacilityId = 12,
                            ProviderFirstName = "Rock",
                            ProviderLastName = "Sharville",
                            ProviderPhoneNumber = 5864186454L,
                            SpecialtyId = 8
                        },
                        new
                        {
                            ProviderId = 28,
                            FacilityId = 13,
                            ProviderFirstName = "Dani",
                            ProviderLastName = "Broadwell",
                            ProviderPhoneNumber = 4221047432L,
                            SpecialtyId = 10
                        },
                        new
                        {
                            ProviderId = 29,
                            FacilityId = 14,
                            ProviderFirstName = "Virginia",
                            ProviderLastName = "McAvinchey",
                            ProviderPhoneNumber = 8769325946L,
                            SpecialtyId = 2
                        },
                        new
                        {
                            ProviderId = 30,
                            FacilityId = 15,
                            ProviderFirstName = "Neala",
                            ProviderLastName = "Cianelli",
                            ProviderPhoneNumber = 4504879923L,
                            SpecialtyId = 15
                        },
                        new
                        {
                            ProviderId = 31,
                            FacilityId = 6,
                            ProviderFirstName = "Pooh",
                            ProviderLastName = "Florio",
                            ProviderPhoneNumber = 3317751153L,
                            SpecialtyId = 6
                        },
                        new
                        {
                            ProviderId = 32,
                            FacilityId = 14,
                            ProviderFirstName = "Portia",
                            ProviderLastName = "Treadwell",
                            ProviderPhoneNumber = 3609514708L,
                            SpecialtyId = 14
                        },
                        new
                        {
                            ProviderId = 33,
                            FacilityId = 4,
                            ProviderFirstName = "Tucky",
                            ProviderLastName = "Dreher",
                            ProviderPhoneNumber = 1313561327L,
                            SpecialtyId = 4
                        },
                        new
                        {
                            ProviderId = 34,
                            FacilityId = 15,
                            ProviderFirstName = "Gardie",
                            ProviderLastName = "Drakes",
                            ProviderPhoneNumber = 6921919943L,
                            SpecialtyId = 15
                        },
                        new
                        {
                            ProviderId = 35,
                            FacilityId = 7,
                            ProviderFirstName = "Phillip",
                            ProviderLastName = "Sharville",
                            ProviderPhoneNumber = 9529171778L,
                            SpecialtyId = 7
                        },
                        new
                        {
                            ProviderId = 36,
                            FacilityId = 8,
                            ProviderFirstName = "Byrle",
                            ProviderLastName = "Shuttleworth",
                            ProviderPhoneNumber = 2717398518L,
                            SpecialtyId = 8
                        },
                        new
                        {
                            ProviderId = 37,
                            FacilityId = 14,
                            ProviderFirstName = "Hy",
                            ProviderLastName = "Hamflett",
                            ProviderPhoneNumber = 1206169437L,
                            SpecialtyId = 14
                        },
                        new
                        {
                            ProviderId = 38,
                            FacilityId = 12,
                            ProviderFirstName = "Eadie",
                            ProviderLastName = "Taill",
                            ProviderPhoneNumber = 7997088826L,
                            SpecialtyId = 12
                        },
                        new
                        {
                            ProviderId = 39,
                            FacilityId = 2,
                            ProviderFirstName = "Timi",
                            ProviderLastName = "Kestian",
                            ProviderPhoneNumber = 2894355254L,
                            SpecialtyId = 2
                        },
                        new
                        {
                            ProviderId = 40,
                            FacilityId = 11,
                            ProviderFirstName = "Gearalt",
                            ProviderLastName = "Dows",
                            ProviderPhoneNumber = 7618424391L,
                            SpecialtyId = 11
                        },
                        new
                        {
                            ProviderId = 41,
                            FacilityId = 6,
                            ProviderFirstName = "Lisa",
                            ProviderLastName = "Simons",
                            ProviderPhoneNumber = 5821908432L,
                            SpecialtyId = 1
                        },
                        new
                        {
                            ProviderId = 42,
                            FacilityId = 12,
                            ProviderFirstName = "Leroy",
                            ProviderLastName = "Gerkins",
                            ProviderPhoneNumber = 2337452877L,
                            SpecialtyId = 1
                        },
                        new
                        {
                            ProviderId = 43,
                            FacilityId = 1,
                            ProviderFirstName = "Ki'Nir",
                            ProviderLastName = "Habadayah",
                            ProviderPhoneNumber = 4997874451L,
                            SpecialtyId = 1
                        },
                        new
                        {
                            ProviderId = 44,
                            FacilityId = 12,
                            ProviderFirstName = "James",
                            ProviderLastName = "Sloan",
                            ProviderPhoneNumber = 3261558779L,
                            SpecialtyId = 1
                        },
                        new
                        {
                            ProviderId = 45,
                            FacilityId = 1,
                            ProviderFirstName = "Karina",
                            ProviderLastName = "Silkya",
                            ProviderPhoneNumber = 6674219116L,
                            SpecialtyId = 1
                        });
                });

            modelBuilder.Entity("HealthPairDataAccess.DataModels.Data_Specialty", b =>
                {
                    b.Property<int>("SpecialtyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasColumnType("character varying(80)")
                        .HasMaxLength(80);

                    b.HasKey("SpecialtyId");

                    b.ToTable("Specialties");

                    b.HasData(
                        new
                        {
                            SpecialtyId = 1,
                            Specialty = "Ophthalmologist"
                        },
                        new
                        {
                            SpecialtyId = 2,
                            Specialty = "Dermatologist"
                        },
                        new
                        {
                            SpecialtyId = 3,
                            Specialty = "Cardiologist"
                        },
                        new
                        {
                            SpecialtyId = 4,
                            Specialty = "Urologist"
                        },
                        new
                        {
                            SpecialtyId = 5,
                            Specialty = "Gastroenterologist"
                        },
                        new
                        {
                            SpecialtyId = 6,
                            Specialty = "Psychiatrist"
                        },
                        new
                        {
                            SpecialtyId = 7,
                            Specialty = "Internist"
                        },
                        new
                        {
                            SpecialtyId = 8,
                            Specialty = "Neurologist"
                        },
                        new
                        {
                            SpecialtyId = 9,
                            Specialty = "Endocrinologist"
                        },
                        new
                        {
                            SpecialtyId = 10,
                            Specialty = "Otolaryngologist"
                        },
                        new
                        {
                            SpecialtyId = 11,
                            Specialty = "Orthopedist"
                        },
                        new
                        {
                            SpecialtyId = 12,
                            Specialty = "Pediatrician"
                        },
                        new
                        {
                            SpecialtyId = 13,
                            Specialty = "Anesthesiologist"
                        },
                        new
                        {
                            SpecialtyId = 14,
                            Specialty = "Pulmonologist"
                        },
                        new
                        {
                            SpecialtyId = 15,
                            Specialty = "Proctologist"
                        });
                });

            modelBuilder.Entity("HealthPairDataAccess.DataModels.Data_Appointment", b =>
                {
                    b.HasOne("HealthPairDataAccess.DataModels.Data_Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthPairDataAccess.DataModels.Data_Provider", "Provider")
                        .WithMany("Appointments")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HealthPairDataAccess.DataModels.Data_InsuranceProvider", b =>
                {
                    b.HasOne("HealthPairDataAccess.DataModels.Data_Insurance", "Insurance")
                        .WithMany("InsuranceProviders")
                        .HasForeignKey("InsuranceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthPairDataAccess.DataModels.Data_Provider", "Provider")
                        .WithMany("InsuranceProviders")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HealthPairDataAccess.DataModels.Data_Patient", b =>
                {
                    b.HasOne("HealthPairDataAccess.DataModels.Data_Insurance", "Insurance")
                        .WithMany("Patients")
                        .HasForeignKey("InsuranceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HealthPairDataAccess.DataModels.Data_Provider", b =>
                {
                    b.HasOne("HealthPairDataAccess.DataModels.Data_Facility", "Facility")
                        .WithMany("Providers")
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthPairDataAccess.DataModels.Data_Specialty", "Specialty")
                        .WithMany("Providers")
                        .HasForeignKey("SpecialtyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
